spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: delivery-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST_DELIVERY}/team7
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
  kafka:
    bootstrap-servers: ${KAFKA_SERVER_URL}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 19094

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_URL}/eureka/