server:
  port: 19091

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: user-service
  data:
    redis:
      host: ${REDIS_HOST_USER}
      port: 6379
      password: 1234
  datasource:
    driver-class-name: org.postgresql.Driver
    username: team7
    password: 1234
    url: jdbc:postgresql://${POSTGRES_HOST_USER}/team7
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_URL}/eureka/
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret:
    key: RyYSFXj0FFZDdly9yOmEspG1rMk0++GjPUZLUSZzN1IyZaAEq8CNXjO3NxsfS1GlFOfYVUodjBocRWhC6+Wbog==
  access:
    exp: 3600000
  refresh:
    exp: 36000000