spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${POSTGRES_HOST_HUB}/team7
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
  application:
    name: hub-service
  data:
    redis:
      host: localhost
      port: ${REDIS_PORT}
  cache:
    type: redis

server:
  port: 19092

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:19090/eureka/
  instance:
    hostname: localhost
kakao:
  rest:
    api:
      key: ${KAKAO_KEY}

logging:
  level:
    org.springframework.cache: DEBUG

jwt:
  secret:
    key: ${JWT_SECRET_KEY}