spring:
  application:
    name: product-service

  cloud:
    discovery:
      enabled: true
      netflix:
        eureka:
          client:
            service-url:
              defaultZone: http://eureka-server:8761/eureka/
        instance:
          hostname: product-service
          prefer-ip-address: true

  datasource:
    url: jdbc:postgresql://postgres-db:5432/productdb
    username: postgres
    password: password
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  feign:
    hystrix:
      enabled: true
    client:
      config:
        default:
          loggerLevel: full

  management:
    endpoints:
      web:
        exposure:
          include: "*"
    health:
      diskspace:
        enabled: true
      db:
        enabled: true

server:
  port: 8080