spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST_PRODUCT}/team7
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  feign:
    hystrix:
      enabled: true
    client:
      config:
        default:
          loggerLevel: full

  management:
    endpoints:
      web:
        exposure:
          include: "*"
    health:
      diskspace:
        enabled: true
      db:
        enabled: true

server:
  port: 19095

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_URL}/eureka/