spring:
  application:
    name: ai-service
  cloud:
    discovery:
      enabled: true
      netflix:
        eureka:
          client:
            service-url:
              defaultZone: http://eureka-server:8761/eureka/
        instance:
          hostname: ai-service
          prefer-ip-address: true
  datasource:
    url: jdbc:postgresql://postgres-db:5432/aiservice
    username: postgres
    password: password
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  feign:
    hystrix:
      enabled: true
    client:
      config:
        default:
          loggerLevel: full
  management:
    endpoints:
      web:
        exposure:
          include: "*"
    health:
      diskspace:
        enabled: true
      db:
        enabled: true
gemini:
  api:
    baseurl: ${gemini.baseurl}
    key: ${googleai.api.key}
server:
  port: 8080